---
#
# Example play:
#
# - name: Install Newrelic Infrastructure agent
#   hosts: all
#   sudo: True
#   gather_facts: True
#   roles:
#     - newrelic-infra-unizin

- name: get ec2 metadata
  ec2_facts:

- name: set new relic display name variable
  set_fact:
    unizin_setup_nria_display_name: "{{ software_key_prefix }}-{{ environment_name }}-{{ ansible_ec2_instance_id }}"
  when: software_key_prefix is defined and environment_name is defined

- name: add apt key for New Relic
  apt_key:
    url: "{{ NEWRELIC_DEBIAN_KEY_URL }}"
    state: present

- name: install apt repository for New Relic
  apt_repository:
    repo: "{{ NEWRELIC_DEBIAN_REPO }}"
    state: present
    update_cache: yes

- name: install New Relic agent
  apt:
    name: "{{ NEWRELIC_DEBIAN_PKG }}"
    install_recommends: yes
    state: present
    update_cache: yes

- name: configure New Relic agent
  template:
    src: newrelic-infra.yml.j2
    dest: "{{ NEWRELIC_CONFIG_PATH }}"
    owner: "newrelic"
    group: "newrelic"
    mode: 0600

- name: insert display_name into New Relic configuration file
  lineinfile:
    dest: "{{ NEWRELIC_CONFIG_PATH }}"
    line: "display_name: {{ unizin_setup_nria_display_name }}"
  when: unizin_setup_nria_display_name is defined

- name: setup agent service
  service: name=newrelic-infra state=started enabled=yes

