
- name: Bootstrap app server(s)
  hosts: edxapp
  gather_facts: false
  become: true
  vars:
    app_stack: "{{ hostvars['localhost']['app_stack'] }}"
  roles:
    - role: python
      when: app_stack|changed


# Stateless app server configuration, designed to be used with external mysql,
# mongo, rabbitmq, and elasticsearch services.

- name: Configure instances
  hosts: edxapp
  gather_facts: true
  become: true
  vars_files:
    - [ "../params/{{ short_name }}-{{ env }}.yml", "../params/unizin-dev.yml" ]
  vars:
    DOMAIN: "{{ hostvars['localhost']['DOMAIN'] }}"
    PREVIEWURL: "{{ hostvars['localhost']['PREVIEWURL'] }}"
    S3STORAGEBUCKET: "{{ hostvars['localhost']['S3STORAGEBUCKET'] }}"
    EDXAPP_AWS_ACCESS_KEY_ID: "{{ hostvars['localhost']['EDXAPP_AWS_ACCESS_KEY_ID'] }}"
    EDXAPP_AWS_SECRET_ACCESS_KEY: "{{ hostvars['localhost']['EDXAPP_AWS_SECRET_ACCESS_KEY'] }}"
    COMMON_MYSQL_MIGRATE_USER: "{{ hostvars['localhost']['COMMON_MYSQL_MIGRATE_USER'] }}"
    COMMON_MYSQL_MIGRATE_PASS: "{{ hostvars['localhost']['COMMON_MYSQL_MIGRATE_PASS'] }}"
    EDXAPP_MYSQL_PASSWORD: "{{ hostvars['localhost']['EDXAPP_MYSQL_PASSWORD'] }}"
    EDXAPP_MYSQL_PASSWORD_READ_ONLY: "{{ hostvars['localhost']['EDXAPP_MYSQL_PASSWORD_READ_ONLY'] }}"
    EDXAPP_MYSQL_PASSWORD_ADMIN: "{{ hostvars['localhost']['EDXAPP_MYSQL_PASSWORD_ADMIN'] }}"
    MONGO_ADMIN_PASSWORD: "{{ hostvars['localhost']['MONGO_ADMIN_PASSWORD'] }}"
    EDXAPP_MONGO_PASSWORD: "{{ hostvars['localhost']['EDXAPP_MONGO_PASSWORD'] }}"
    FORUM_MONGO_PASSWORD: "{{ hostvars['localhost']['FORUM_MONGO_PASSWORD'] }}"
    EMAIL_HOST_USER: "{{ hostvars['localhost']['EMAIL_HOST_USER'] }}"
    EMAIL_HOST_PASSWORD: "{{ hostvars['localhost']['EMAIL_HOST_PASSWORD'] }}"
    app_stack: "{{ hostvars['localhost']['app_stack'] }}"
    RdsEndpointAddress: "{{ hostvars['localhost']['RdsEndpointAddress'] }}"
    migrate_db: 'yes'
    openid_workaround: true
    EDXAPP_LMS_NGINX_PORT: '80'
    ENABLE_ECOMMERCE: false  # Disable by default
  roles:

    # Ensure we have no known security vulnerabilities
    - role: security
      when: app_stack|changed

    # Server setup
    - role: swapfile
      when: app_stack|changed

    # Nginx reverse proxy
    - role: nginx
      nginx_sites:
      - certs
      - cms
      - lms
      nginx_default_sites:
      - lms
      when: app_stack|changed

    # Main EdX application
    # https://github.com/edx/edx-platform
    - role: edxapp
      celery_worker: true
      when: app_stack|changed

    - role: edxapp
      when: app_stack|changed

    # Notifications service
    # https://github.com/edx/notifier
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: '5'
      when: app_stack|changed

    - role: demo
      when: app_stack|changed

    - role: certs
      when: app_stack|changed

    - role: memcache
      when: app_stack|changed

