# Create Open edX IAM and S3 stacks
#
# Usage:
#   ansible-playbook -vvvv create_base_stacks.yml -e env=... -e short_name=...
---
- hosts: localhost
  vars_files:
    - [ "params/{{ short_name }}-{{ env }}-base.yml", "params/unizin-dev-base.yml" ]
  tasks:
    - name: create Open edX IAM stack
      cloudformation:
        stack_name: "Open-edX-{{ full_name }}-IAM"
        region: "us-east-1"
        state: "present"
        template: "cfn/iam-stack.template"
        template_parameters:
          EnvironmentName: "{{ env }}"
          UniversityShortName: "{{ short_name }}"
        tags:
          Stack: "Open-edX-{{ full_name }}-IAM"
          Project: "openedx"

    - name: create Open edX S3 stack
      cloudformation:
        stack_name: "Open-edX-{{ full_name }}-S3"
        region: "us-east-1"
        state: "present"
        template: "cfn/s3-stack.template"
        template_parameters:
          EnvironmentName: "{{ env }}"
          UniversityShortName: "{{ short_name }}"
        tags:
          Stack: "Open-edX-{{ full_name }}-S3"
          Project: "openedx"


    - name: create subfolders inside s3 bucket
      s3:
        bucket: "unizin-{{ env }}-openedx-{{ short_name }}"
        object: "{{ item }}"
        mode: create
      with_items:
        - /badges
        - /grades
        - /images
        - /media
...
