# Creates one RDS instance and 4 EC2 instances.
# For details and to modify go to defaults/main.yml 
# for the relevant role.
# Usage:
#   ansible-playbook ./create_resources.yml -e university_short_name=...
---
- name: deploy edx infrastructure
  hosts: all
  vars:
     name: "{{ university_short_name }}"
     app_count: 1
  vars_files:
    - [ "params/{{ university_short_name }}.yml", "params/unizin.yml" ]
  roles: 
    - create_rds
    - create_instances
...
