# Create Open edX IAM stack
#
# Usage:
#   ansible-playbook -vvvv create_iam_stack.yml -e short_name=...
---
- hosts: localhost
  vars_files:
    - [ "params/{{ short_name }}-base.yml", "params/unizin-base.yml" ]
  tasks:
    - name: create Open edX IAM stack
      cloudformation:
        stack_name: "Open-edX-{{ full_name }}-IAM"
        region: "us-east-1"
        state: "present"
        template: "cfn/iam-stack.template"
        template_parameters:
          UniversityShortName: "{{ short_name }}"
        tags:
          Stack: "Open-edX-{{ full_name }}-IAM"
          Project: "openedx"
...
