# Create Open edX data stack
#
# Usage:
#   ansible-playbook -vvvv create_stacks.yml -e env=... -e short_name=... -e bypass=...
#     bypass is an optional parameter, its default value is short_name
---
- hosts: localhost
  vars_files:
    - [ "params/{{ short_name }}-{{ env }}.yml", "params/unizin-dev.yml" ]
  tasks:
    - name: default value for optional bypass parameter
      set_fact:
        bypass: "{{ short_name }}"
      when: bypass is undefined

    - name: default value for optional bypass parameter
      set_fact:
        domain_prefix: "{{ bypass }}"
        preview_prefix: "{{ bypass }}_preview"
      when: ("{{ env }}" == "prod")

    - name: default value for optional bypass parameter
      set_fact:
        domain_prefix: "{{ bypass }}-openedx"
        preview_prefix: "{{ bypass }}-preview-openedx"
      when: ("{{ env }}" == "dev")

    - name: set DOMAIN, PREVIEWURL, S3ST0RAGEBUCKET, NEWRELIC_LICENSE_KEY
      set_fact:
        DOMAIN: "{{ domain_prefix }}.{{ hosted_zone_minus_period }}"
        SOFTWARE_KEY_PREFIX: "{{ domain_prefix }}.{{ hosted_zone_minus_period }}"
        PREVIEWURL: "{{ preview_prefix }}.{{ hosted_zone_minus_period }}"
        S3STORAGEBUCKET: "unizin-{{ env }}-openedx-{{ bypass }}"
        NEWRELIC_LICENSE_KEY: "{{ NEWRELIC_LICENSE_KEY }}"


- include: includes/create_security_stack.yml

- include: includes/create_rds_stack.yml
- include: includes/provision_rds.yml

- include: includes/create_data_servers.yml
- include: includes/provision_data_servers.yml

- include: includes/create_app_servers.yml
- include: includes/provision_app_servers.yml

...
