# Creates one RDS instance and 4 EC2 instances.
# For details and to modify go to defaults/main.yml 
# for the relevant role.
# Usage:
#   ansible-playbook -vvvv create_resources.yml -e university_short_name=...
---
- name: deploy edx infrastructure
  hosts: all
  vars:
     name: "{{ university_short_name }}"
     app_count: 1
  vars_files:
    - [ "params/{{ university_short_name }}.yml", "params/unizin.yml" ]
  roles: 
    - create_rds
    - { role: create_instance, instance: t2.small,  vol_size: 8,  instance_name: "openedx-{{ name }}-mongo-1", sg: "{{ mongo_sg }}", description: "MongoDB PRIMARY"}
    - { role: create_instance, instance: t2.small,  vol_size: 8,  instance_name: "openedx-{{ name }}-mongo-2", sg: "{{ mongo_sg }}", description: "MongoDB SECONDARY"}
    - { role: create_instance, instance: t2.large,  vol_size: 8,  instance_name: "openedx-{{ name }}-common",  sg: "{{ common_sg }}", description: "Common server"}
    - { role: create_instance, instance: t2.medium, vol_size: 16, instance_name: "openedx-{{ name }}-app",     sg: "{{ edxapp_sg }}", description: "EdX app server"}
...
