---
- name: Configure RabbitMQ, ElasticSearch and xqueue
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
  roles:
    - rabbitmq
    - elasticsearch
    - role: nginx
      nginx_sites:
      - xqueue
    - role: xqueue
      update_users: True
...
